### PR TITLE
declare keyring a stable feature

### PR DESCRIPTION
**Pull request by esc**
Many people have used this again and again and have tested it extensively.
Let's promote it so that it is no longer an experimental feature.

### CODE REVIEW

**Comment by esc** [comment]
Cloud someone with a Mac please tests this? I am not sure if the `secretstorage` dependency needed on Linux will install cleanly on Mac OSX.

**Comment by esc** [comment]
@schlomo any chance you could look at this?

**Comment by schlomo** [comment]
@esc after I can install it with `pip`, gladly.

**Comment by mriehl** [comment]
@esc you can try to install it on travis with the objective c environment. This runs on osx infrastructure afaik

**Comment by esc** [comment]
In principle you should be able to pip install with:

```
$ pip install git+ssh:[//git@github.com:esc/afp-cli/feature/promote_keyring
```

However this currently does not work for afp-cli since it lacks a special `setup.py` to masquerade the fact that it is a pybuilder project. 

@mriehl I have seen that, `pyb --start-project` now auto-generates a `setup.py`, but I haven't yet seen a task to generate (or re-generate it for existing projects). I presume such a feature would be worthwhile having?

**Comment by esc** [comment]
@mriehl just found `--update-project` it works fine but I was expecting it to print that it succeeded. Also, the completion didn't seem to pick up on it.

**Comment by esc** [comment]
I fixed the pyb zsh completion here: https://github.com/pybuilder/pybuilder-completions/pull/1

I'll make this pip installable tomorrow, when back at the office.

Good night!

**Comment by esc** [comment]
@schlomo you can now install this pull-request using:

```
$ pip install git+git://github.com/esc/afp-cli.git@feature/promote_keyring
```

**Comment by esc** [comment]
Or anyone else with a mac for that matter.

**Comment by esc** [comment]
@schlomo ping!

**Comment by schlomo** [comment]
I installed it and it works. What else should I test?

**Pull request merged**
