### PR TITLE
Keychain

### PR DESCRIPTION
**Pull request by esc**
This implements support for the python 'keychain' module.

### CODE REVIEW

**Comment by esc** [comment]
This is experimental support for the 'keychain' module:

https://pypi.python.org/pypi/keyring

It still has some caveats, things to think about:
- Apparently it supports OSX and Windows too but I have only tested gnome-keychain.
- It looks for the password, and prompts for it and saves it if not found
- You can use `seahorse` to view the password entry.
- Keychain is pip installable, but the `PyGObject` thing isn't. (https://wiki.gnome.org/action/show/Projects/PyGObject?action=show&redirect=PyGObject)
- This means, you need to make a venv with `--use-site-packages` and install `afp-cli` and `keychain` there. Should probably be documented.
- If you don't have the `PyGObject` thing installed, it uses something else, but I haven't worked out what.
- There is lightweight replacement for `PyGObject` called `pgi`but you need to hack `keychain` and then it can only set the password, not retreive it. (https://pypi.python.org/pypi/pgi)

I'd appreciate if some of the tech-savy ones amongst you could give it a shot and provide feedback.

**Comment by esc** [comment]
Also, I had to vendor bottledaemon again, because:

https://github.com/ImmobilienScout24/afp-cli/commit/900dec1dd33fa9fbd30c561fadc775924b1a0623

**Comment by esc** [comment]
And oh yeah, sorry, but I didn't have any time to write tests, but will before the merge. _evilgrin_

**Comment by mriehl** [comment]
@esc you are my hero. As an end user I am using a global install of api-cli anyway so reliance on system site packages is not an issue for me.

**Comment by esc** [comment]
@mriehl no worries! It was trivial to implement once I understood where the packages come from and how to install them

**Comment by esc** [comment]
@mriehl also, let me know if it works for you!

**Comment by esc** [comment]
Regarding the coverage and tests, the `cli.py` file is excluded from the coverage, but contains a bunch of code.. should probably deal with this somehow.

**Comment by esc** [comment]
Guess I'll be merging this and refactoring it with more pull-requests.

**Pull request merged**
