### PR TITLE
closes #39 + raising coverage

### LINKED ISSUE #39: Add an option to set only the server
Use `-s,--server` on the command line interface and `server` in the config to configure on the name of the server and not the full `--api-url`.

I guess `api-url` should take precedence if given in the config-file or on the command-line, might be a bit tricky to handle that correctly.

### PR DESCRIPTION
**Pull request by karolyi**
a couple more commits upcoming for #39

### CODE REVIEW

**Comment by esc** [comment]
Would probably be wise to add some documentation in the README too.

**Comment by esc** [comment]
Also, what happens if there is an `api-url` in the config file, but `--server` is given on the command line? :evilgrin:

**Comment by karolyi** [comment]
@esc as per https://github.com/ImmobilienScout24/afp-cli/pull/50/files#diff-2e8e478fe386a8496330bb497b3eb0c1R56, `--api-url` and `api_url` always takes precedence.

Isn't this the desired behavior?

**Comment by esc** [comment]
Yeah, I am not sure. I guess the correct behaviour is that command-line always overrides config also for mutually exclusive options. Imagine I had `api-url` defined in the config and wanted to test with an alternative `server`. But then again, I think this is such a corner case, perhaps we should only fix it if someone complains.

**Comment by karolyi** [comment]
@schlomo has some second thoughts on the `sanitize_host` function, I'll wait for his input and if he agrees on my suggestion, I'll merge this stuff into master, continuing the milestone branch afterwards.

**Comment by esc** [comment]
@karolyi sounds good to me.

**Comment by esc** [comment]
@karolyi sorry, didn't get around to it yet.

**Pull request merged**
