### PR TITLE
resolves #33, add automatic versioning by pybuilder

### LINKED ISSUE #33: Cannot check version and build time of installed afp-cli
Currently the only place the version is stored is in the `build.py`. This means the cli can not report it's own version with `--version` for example.

### PR DESCRIPTION
**Pull request by karolyi**
- In order for this commit to go through, a pull request involving
  pybuilder cram plugin update needs to be merged:
  https://github.com/pybuilder/pybuilder/pull/318

### CODE REVIEW

**Comment by karolyi** [comment]
solves #6 too

**Comment by esc** [comment]
pybuilder/pybuilder#318 has been merged and a new release cut

**Comment by esc** [comment]
Re-running travis.

**Comment by esc** [comment]
Meh, pybuilder release didn't quite work.

**Comment by esc** [comment]
Re-running again.

**Comment by esc** [comment]
Damn, it's bust for Python2.6..

**Comment by esc** [comment]
Here we go!

**Pull request merged**
