### PR TITLE
remove bottledaemon vendoring

### PR DESCRIPTION
**Pull request by esc**
python-daemon has been fixed in version 2.1.1, no more need to vendor this
stuff

https://alioth.debian.org/scm/loggerhead/python-daemon/trunk/view/head:/ChangeLog#L10

### CODE REVIEW

**Comment by esc** [comment]
Let's see what travis says.

**Comment by esc** [comment]
Python 2.6 is still bust. meh :/

**Comment by esc** [comment]
I'll fix and release pybuilder on monday.

**Comment by snordhausen** [comment]
Pybuilder is already [fixed](https://github.com/pybuilder/pybuilder/pull/333), just waiting for a release.

**Pull request merged**
