### PR TITLE
Feature: zsh completion

### PR DESCRIPTION
**Pull request by esc**
it's a bit ugly, but fully functional, I can assure you that!

cc @mriehl

### CODE REVIEW

**Comment by schlomo** [comment]
Cool! What about bash completion?

**Comment by esc** [comment]
@schlomo pull-requests welcome? :grinning:

**Comment by schlomo** [comment]
@esc I meant similar to the completer for the [aws-cli](https://github.com/aws/aws-cli/tree/develop/bin)

**Comment by esc** [comment]
@schlomo ah yes, that is a possibility. BTW: there is also https://github.com/kislyuk/argcomplete but it's not compatible with docopt.

**Comment by esc** [comment]
I should probably also mention, that this zsh completion will only work for the new version of the afp-cli.

**Comment by mriehl** [comment]
Any reason this was not merged into master yet?

**Comment by esc** [comment]
Not yet sure how to distribute it properly, any ideas on that front? Also it was kind of experimental until now.

**Comment by mriehl** [comment]
For pybuilder we ship the completions with `sudo pip install`. The package consists of completions we put into the global zsh directory `/etc/zsh/functions` I think?

I wasn't able to find a user-specific directory that works for all zsh distributions.

But the best solution is probably building debs with a snakepitted afp.

**Comment by esc** [comment]
debs yes -- snakepit, maybe. It's a desktop tool so we can assume an up-to-date python and dependencies, not sure why we would want snakepit in this case.

**Comment by esc** [comment]
@mriehl 

```
zsh» print -rl - $fpath
/home/esc/git/zsh-completions/src
/usr/share/grml/zsh/functions
/usr/share/grml/zsh/completion
/usr/local/share/zsh/site-functions
/usr/share/zsh/vendor-functions
/usr/share/zsh/vendor-completions
/usr/share/zsh/functions/Calendar
/usr/share/zsh/functions/Chpwd
/usr/share/zsh/functions/Completion
/usr/share/zsh/functions/Completion/AIX
/usr/share/zsh/functions/Completion/BSD
/usr/share/zsh/functions/Completion/Base
/usr/share/zsh/functions/Completion/Cygwin
/usr/share/zsh/functions/Completion/Darwin
/usr/share/zsh/functions/Completion/Debian
/usr/share/zsh/functions/Completion/Linux
/usr/share/zsh/functions/Completion/Mandriva
/usr/share/zsh/functions/Completion/Redhat
/usr/share/zsh/functions/Completion/Solaris
/usr/share/zsh/functions/Completion/Unix
/usr/share/zsh/functions/Completion/X
/usr/share/zsh/functions/Completion/Zsh
/usr/share/zsh/functions/Completion/openSUSE
/usr/share/zsh/functions/Exceptions
/usr/share/zsh/functions/MIME
/usr/share/zsh/functions/Misc
/usr/share/zsh/functions/Newuser
/usr/share/zsh/functions/Prompts
/usr/share/zsh/functions/TCP
/usr/share/zsh/functions/VCS_Info
/usr/share/zsh/functions/VCS_Info/Backends
/usr/share/zsh/functions/Zftp
/usr/share/zsh/functions/Zle
/home/esc/gw/pybuilder-completions
/home/esc/gw/conda-zsh-completion
/home/esc/gw/git-annex-zsh-completion
```

**Comment by mriehl** [comment]
> not sure why we would want snakepit in this case

because there are dependencies. Maybe some other tool shipped with ubuntu requires a different version of `requests`, or maybe I'll be running python 4.0 in the future before the tool can deal with it.
Targeting the desktop means you have even less control over what is installed so a self-satisfying snakepitted program is better IMHO.

**Comment by esc** [comment]
Just rebased this, will now merge and make a new issue for delivering the completion with the package via PyPi.

**Pull request merged**
