### PR TITLE
Issue fix 43

### PR DESCRIPTION
**Pull request by karolyi**
fixing issue #43, utf8 handling is generally a PITA with py2

### CODE REVIEW

**Comment by esc** [comment]
I still haven't tried this out but I don't feel comfortable with the amount of reformatting and beautification. First, it makes the diff in the pull-request quite hard to read and second I do like the way the imports are formatted and spent quite a lot time making them look nice.

**Comment by esc** [comment]
Maybe in future you could split feature/fix and beautifcation into two pull requests.

**Comment by esc** [comment]
Anyway, let me get this tried manually today.

**Comment by karolyi** [comment]
This does not work yet, travis produces absolutely weird errors via the request library which I'm unable to reproduce locally (which means it works locally, not just the tests but `afp-cli` itself installed and tried out).

We'll use another approach to fix this bug.

**Comment by karolyi** [comment]
The import beautifications are done by [isort](https://github.com/timothycrosley/isort).

**Comment by esc** [comment]
Yes, I know about isort, I basically stopped "beautifying" other peoples code after I watched;

http://pyvideo.org/video/3511/beyond-pep-8-best-practices-for-beautiful-inte

Still the point about splitting beautifcation and bugfix remains.

**Comment by esc** [comment]
Will close in favour of #47

**Pull request closed without merging**
